language: python

python:
  - 3.6

matrix:
  include:
    addons:
      apt:
        packages:
          - python-scipy


install:
  - pip install coveralls

script:
  - coverage run setup.py test

after_success:
  - coveralls

